### ISSUE TITLE
Different Behaviour

### ISSUE THREAD

**Issue by NR8124** [tserumula/DbCleanerforWhatsapp#4]
Here is the SS of my realme 7 device with android 11 and WhatsApp installed. But unfortunately it is behaving very differently.. showing some blank UI and no detection of db files... 

my whatsapp db path is :: **storage/android/media/com.whatsapp/WhatsApp/Databases**

**Comment by tserumula** [comment]
Looks like there was a change in Android 11. App was expecting the folder to be at :
**storage/WhatsApp/Databases**

Will add fix very soon.

**Comment by tserumula** [comment]
Hi. I have updated the folder paths. Please use APK from latest release and let me know if issue is resolved.

**Comment by NR8124** [comment]
The issue is still the same

![Screenshot_2022-07-17-20-34-25-03_9af085882b85bd1c89c05650aac52004](https://user-images.githubusercontent.com/88180887/179404401-a3953e9e-8c7b-4c9e-8625-bc643c7e965d.jpg)

**Comment by tserumula** [comment]
In your new screenshot the Whatsapp folder has been detected but the app doesn't see any files to clear at this stage.

*Check how many files you have in `storage/android/media/com.whatsapp/WhatsApp/Databases`
* If just one file then take note that the app does not count/ delete the main Whatsapp backup file. It will clear everything else in that folder except `msgstore.db.cryptXX` file.

* You can test this by copying some random files into `storage/android/media/com.whatsapp/WhatsApp/Databases` then go back to the app and refresh UI. It should show the files.

* You should consider **turning off Auto Cleanup** for now because if enabled the app will always clear the files at 3AM everyday and the UI will remain empty

**Comment by NR8124** [comment]
i tested what u said and i have atleast 4 to 5 files at that location.. but still in app its showing that nothing to clear

**Comment by TPS** [comment]
From Android 11, there're multiple levels of Storage Permission.  It looks like the app is asking for Media Only, but needs to be asking for All Files.

**Comment by tserumula** [comment]
@TPS  Noted. I will add this soon and get back.
But if you have already done it you can send pull-request

**Comment by tserumula** [comment]
Hello. I have added the changes to the project. Please use the APK from this [pre-release](https://github.com/tserumula/DbCleanerforWhatsapp/releases/tag/v1.2.0-beta) and let me know if the problem has been fixed for you.

I tested this using the Android 11 Emulator and it seemed to work fine on my side. Had to add a new permission `MANAGE_EXTERNAL_STORAGE` to get it to work because external storage is restricted from Android 11. Anyway, let me know if it is now working

**Comment by NR8124** [comment]
The issue has been completely resolved.. now i can see ghe files and was able to clear all the stuffs

But there was just one things my phone was in dark mode so app was also opened in dark mode by default 

And in dark mode the file names was not visible
Background and text color both were black

So just make it visible in final release...

Btw appreciate your efforts man 🙌

**Comment by tserumula** [comment]
Hi. All has been fixed. Please see [latest-release](https://github.com/tserumula/DbCleanerforWhatsapp/releases/tag/v1.3.0)

I will now close this issue. If you experience any new problems you can open a new one.
Take care :+1:
